### PR TITLE
Style proposal

### PR DESCRIPTION
**Pull request by ianaya89**
- Add some links and bolds 
- Add index and subindex to FAQ
- Add index to README
- Rename "be good" file.

### CODE REVIEW

**Comment by ianaya89** [comment]
@gabmontes I think makes sense. I can add these changes too.

**Comment by ianaya89** [comment]
@tparvu I don't think so, it has the link to file in master branch. And there is not `BE_GOOD.md` yet.

**Comment by Dareknotderek** [comment]
Sorry about that everyone, accidentally clicked the close branch button!

**Comment by tparvu** [comment]
@ianaya89 right but it looks like the link is to `BEE_GOOD.md` not `BE_GOOD.md` ??

**Comment by ianaya89** [comment]
@tparvu You bet 😅. Thanks!

**Comment by Dareknotderek** [comment]
@tparvu good catch

**Comment by jgarzik** [comment]
> What about naming all the markdown files in all-uppercase as usual?
@gabmontes This doesn't apply to all files.  
Historical background:  Markdown takes its lead and origins from source code repositories full of ASCII text files.   Traditionally you might see a README or INSTALL file in all-caps, because those files are intended to be highlighted for the reader during `ls` operations as key stand-out pieces of documentation.
Thus, README.md is automatically captured by github, and is all-caps following this tradition.  FAQ.md is all-caps because it's an acronym.  Other files should be capitalized normally (e.g. BeGood.md)

**Comment by ianaya89** [comment]
@jgarzik @gabmontes What do you think about naming files (except for the exceptions like the README) with `kebab-case.md` ? I think is

**Comment by gabmontes** [comment]
> Historical background: Markdown takes its lead and origins from source code repositories full of ASCII text files. Traditionally you might see a README or INSTALL file in all-caps, because those files are intended to be highlighted for the reader during ls operations as key stand-out pieces of documentation

@jgarzik thanks so much for the background! I was wrong these whole time then :)

**Pull request merged**
